<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8"/>
		<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
		<meta name="description" content=""/>
		<meta name="author" content=""/>
		<!-- Bootstrap core CSS -->
		<link href="../../../css/bootstrap.css" rel="stylesheet"/>
		<link href="../../../css/quizzer.css" rel="stylesheet"/>
		<!-- Custom styles for this template -->
        <title>Quizzer</title>
		<link rel="shortcut icon" href="../../../images/favicon.png"/>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top">
		  <div class="container">
			<div class="navbar-header">
			  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			  </button>
			  <a class="navbar-brand" href="/">Quizzer</a>
			</div>
			<div class="navbar-collapse collapse">
			  <ul class="nav navbar-nav">
				<!--<li class="active"><a href="#">Home</a></li>-->
				<li><a href="/user/sign-up">Signup</a></li>
				<li><a href="/about">About</a></li>
				<li><a href="/contact">Contact</a></li>
				<!--<li class="dropdown">
				  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
				  <ul class="dropdown-menu">
					<li><a href="#">Action</a></li>
					<li><a href="#">Another action</a></li>
					<li><a href="#">Something else here</a></li>
					<li class="divider"></li>
					<li class="dropdown-header">Nav header</li>
					<li><a href="#">Separated link</a></li>
					<li><a href="#">One more separated link</a></li>
				  </ul>
				</li>-->
			  </ul>
                          <?php
                            if( $this->loggedOn === false ):?>
                                <form class="navbar-form navbar-right" method="post" action="/user/login">
                                      <div class="form-group">
                                        <input type="text" placeholder="Email" class="form-control" name="email"/>
                                      </div>
                                      <div class="form-group">
                                        <input type="password" placeholder="Password" class="form-control" name="password"/>
                                      </div>
                                      <button type="submit" class="btn btn-success">Sign in</button>
                                </form>
                         <?php else:?>
                            <form class="navbar-form navbar-right" method="post" action="/user/logout">
                               <span class="user-email">
                                    <?php echo $this->user->getEmail() ?>
                                </span>
                                <button type="submit" class="btn btn-success">Log Out</button>
                            </form>
                         <?php endif;?>
			</div><!--/.navbar-collapse -->
		  </div>
		</nav>
		<div id="content">
			<?php echo $this->layout()->content; ?>
		</div>
		<footer>
			<p class="pull-right"><a href="#">Back to top</a></p>
			<p>&#169; 2013 Quizzer <a href="#">&#8226; Privacy</a> <a href="#">&#8226; Terms</a></p>
		</footer>
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
		<script src="../../../js/bootstrap.min.js"></script>
    </body>
</html>
