<div class="jumbotron">
  <div id="contact" class="container">
	<h2><span class="brand">Quizzer</span> - Contact</h2>
	<p>Quizzer was created by:</p>
	<div class="table-responsive">
	  <table class="table">
		<!--<thead>
			<tr>
				<th>Name</th><th>Email</th><th>Twitter</th>
			</tr>
		</thead>-->
		<tbody>
			<tr>
				<td>Marcus Atty</td><td>marcus.atty@gmail.com</td><td>@marcusattyfc</td>
			</tr>
			<tr>
				<td>Matthew Haworth</td><td>matthewh2008@gmail.com</td><td>@matthewhaworth</td>
			</tr>
			<tr>
				<td>Chris Atty</td><td>christopheratty@gmail.com</td><td>@chrisatty</td>
			</tr>
		</tbody>
	  </table>
	</div>
</div>